api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # API methods
    path('api/v1/scrapes/<int:scrap_id>/send', views.SendScrapView.as_view()),
    # path('api/v1/scrapes/send', views.SendMultiple.as_view()),

    path('api/v1/scrapes/', views.ScrapesView.as_view()),
    path('api/v1/scrapes/<int:scrap_id>',views.ScrapView.as_view()),
    path('api/v1/scrapes/<int:scrap_id>/result', views.ScrapResultView.as_view()),

    path('api/v1/urls/', views.UrlsView.as_view()),
    path('api/v1/urls/<int:url_id>/', views.UrlView.as_view()),

    path('api/v1/info/', views.ScraperUserView.as_view()),
]

core/urls.py
from django.urls import path, include

from core import api_views
from . import views

urlpatterns = [
    path('', views.landing_page, name='landing'),

    path('home/', views.home, name='home'),
    path('home/download/', views.download_android, name='download_android_app'),
    path('home/delete/', views.delete_user, name='delete_user'),

    # URL_model paths
    path('urls/', views.scrapurl.get_all, name='get_all_urls'),
    path('urls/delete/', views.scrapurl.delete_all, name='delete_all_urls'),
    path('urls/add/', views.scrapurl.add, name='add_urls'),
    path('urls/upload/', views.scrapurl.upload, name='upload_urls'),

    path('urls/<int:url_id>/', views.scrapurl.get, name='get_url'),
    path('urls/<int:url_id>/update/', views.scrapurl.update, name='update_url'),
    path('urls/<int:url_id>/reset/', views.scrapurl.reset, name='reset_url'),

    # Domain paths
    path('domains/', views.scrapdomain.get_all, name='get_all_domains'),
    path('domains/delete/', views.scrapdomain.delete_all, name='delete_all_domains'),
    path('api/v1/domains/', api_views.DomainsAPIView),

    path('domains/<int:domain_id>/', views.scrapdomain.get, name='get_domain'),
    path('domains/<int:domain_id>/delete/', views.scrapdomain.delete, name='delete_domain'),
    path('domains/<int:domain_id>/update/', views.scrapdomain.update, name='update_domain_config'),
    path('domains/<int:domain_id>/reset/', views.scrapdomain.reset_config, name='reset_domain_config'),
    path('domains/<int:domain_id>/blacklist/', views.scrapdomain.update_blacklist, name='update_domain_blacklist'),

    # Devices paths
    path('devices/', views.scrapdevice.get_all, name='get_all_devices'),
    path('devices/delete/', views.scrapdevice.delete_all, name='delete_all_devices'),

    path('devices/<device_id>/', views.scrapdevice.get, name='get_device'),
    path('devices/<device_id>/delete/', views.scrapdevice.delete, name='delete_device'),
    path('devices/<device_id>/reset/', views.scrapdevice.reset, name='reset_device'),

    # Scrap paths
    path('scrapes/', views.scrapresult.get_all, name='get_all_scrapes'),
    path('scrapes/download/', views.scrapresult.download_all, name='download_all_scrapes'),
    path('scrapes/selected/download/', views.scrapresult.download_selected, name='download_selected_scrapes'),
    path('scrapes/delete/', views.scrapresult.delete_all, name='delete_all_scrapes'),

    path('scrapes/<int:scrap_id>/', views.scrapresult.get, name='get_scrap'),
    path('scrapes/<int:scrap_id>/result', views.scrapresult.get_result, name='get_scrap_result'),
    path('scrapes/<int:scrap_id>/download', views.scrapresult.donwload, name='download_scrap'),
    path('scrapes/<int:scrap_id>/delete', views.scrapresult.delete, name='delete_scrap'),
    path('scrapes/<int:scrap_id>/complain', views.scrapresult.complain, name='complain_scrap'),

    # IP paths
    path('addresses/', views.ip_address.get_all, name='get_all_addresses'),
    path('addresses/<pk>', views.ip_address.get, name='get_address_info'),

    path('signup/', views.auth.SignupView.as_view(), name='signup'),

    path('api/v1/ip/<pk>/',api_views.IPAddressAPIView.as_view(), name='api_manage_ip'),
]

scraper/urls.py
from django.contrib import admin
from django.urls import path, include

from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Scraper API",
        default_version='v1-beta',
        description="Description here",
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),

    path('docs/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('user.urls')),
    path('', include('api.urls')),
    path('', include('android_api.urls')),
    path('', include('administration.urls')),
    path('', include('core.urls'))
]

user/urls.py
from django.urls import path
from . import views

urlpatterns = [

]

core/models/url_models.py
from django.db import models
from django.contrib.auth.models import User


class UrlStatus:
    NOT_SCRAPED = 'no'
    SCRAPING = 'in'
    SCRAPED = 'do'

    CHOICES = (
        (NOT_SCRAPED, 'Not scraped'),
        (SCRAPING, 'Scraping in progress'),
        (SCRAPED, 'Already scraped'),
    )


class UrlPool:
    PUBLIC = 'pub'
    PRIVATE = 'priv'
    WAITING = 'wait'

    CHOICES = (
        (PUBLIC, 'Public'),
        (PRIVATE, 'Private'),
        (WAITING, 'Waiting')
    )


class UrlModel(models.Model):
    url = models.URLField(max_length=500)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    domain = models.ForeignKey('core.DomainModel', on_delete=models.CASCADE)
    status = models.CharField(
        max_length=2,
        choices=UrlStatus.CHOICES,
        default=UrlStatus.NOT_SCRAPED)
    pool = models.CharField(
        max_length=4,
        choices=UrlPool.CHOICES,
        default=UrlPool.WAITING,
    )
    configuration = models.ForeignKey('core.ConfigurationModel', on_delete=models.SET_NULL, null=True, default=None)
    scrap_start_time = models.DateTimeField(default=None, null=True)

    def __str__(self):
        return self.url


class ConfigurationModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    wait_time = models.PositiveIntegerField(default=3)
    scroll_count = models.PositiveIntegerField(default=1)
    scroll_delay = models.PositiveIntegerField(default=1)

core/forms.py
from django.forms import ModelForm

from core.models import ConfigurationModel


class ConfigurationForm(ModelForm):
    class Meta:
        model = ConfigurationModel
        fields = ['wait_time', 'scroll_count', 'scroll_delay']

api/views/UrlView.py
from drf_yasg.utils import swagger_auto_schema
from rest_framework.response import Response
from rest_framework.status import *

from api.serializers import FullUrlInfoSerializer, HttpBadRequestSerializer, PatchUrlRequestSerializer, get_error_desc, \
    UrlInfoSerializer
from core.models import UrlPool, UrlStatus
from core.proxies import Url
from .ScraperApiView import ScraperApiView


class UrlView(ScraperApiView):
    @swagger_auto_schema(
        responses={
            200: FullUrlInfoSerializer,
            401: 'Wrong token or no token provided',
            404: 'URL doesn`t exist'
        },
        operation_id='Get URL information'
    )
    def get(self, request, url_id):
        """
        API call to get the full information about URL.
        """

        scraper = request.user.scraper
        try:
            url = scraper.get_urls().get(pk=url_id)
        except Url.DoesNotExist:
            return Response({'detail': 'URL with such id doesn\'t exist. Maybe it was deleted.'},
                            status=HTTP_404_NOT_FOUND)

        return Response(FullUrlInfoSerializer(url).data)

    @swagger_auto_schema(
        responses={
            200: 'Deleted',
            401: 'Wrong token or no token provided',
            404: 'URL doesn`t exist'
        },
        operation_id='Delete URL'
    )
    def delete(self, request, url_id):
        """
        API call for deleting the URL. If URL is in public pool, and haven't been scraped, you'll get back your token
        """
        scraper = request.user.scraper
        try:
            url = scraper.get_urls().get(pk=url_id)
        except Url.DoesNotExist:
            return Response({'detail': 'URL with such id doesn\'t exist. Maybe it was deleted.'},
                            status=HTTP_404_NOT_FOUND)

        if url.pool == UrlPool.PUBLIC and url.status != UrlStatus.SCRAPED:
            scraper.add_token()
        url.delete()

        return Response({'detail': 'URL deleted.'})

    @swagger_auto_schema(
        request_body=PatchUrlRequestSerializer,
        responses={
            200: UrlInfoSerializer,
            400: HttpBadRequestSerializer,
            401: 'Wrong token or no token provided',
            403: 'Forbidden to move URL',
            404: 'URL doesn`t exist'
        },
        operation_id='Update URL pool'
    )
    def patch(self, request, url_id):
        """
        API call to update URL pool.
        """
        params = PatchUrlRequestSerializer(data=request.data)
        if not params.is_valid():
            return Response(HttpBadRequestSerializer(get_error_desc(params)).data, status=HTTP_400_BAD_REQUEST)
        scraper = request.user.scraper
        try:
            url = scraper.get_urls().get(pk=url_id)
        except Url.DoesNotExist:
            return Response({'detail': 'URL with such id doesn\'t exist. Maybe it was deleted.'},
                            status=HTTP_404_NOT_FOUND)

        moved = False
        add_token = False
        print(params.data['pool'])
        if params.data['pool'] == 'public' and scraper.tokens > 0:
            moved = url.move_to_public()
            if moved:
                scraper.revoke_token()

        elif params.data['pool'] == 'private':
            if url.pool == UrlPool.PUBLIC:
                add_token = True

            moved = url.move_to_private()

        elif params.data['pool'] == 'waiting':
            if url.pool == UrlPool.PUBLIC:
                add_token = True

            moved = url.move_to_waiting()

        print(moved)
        if moved:
            if add_token:
                scraper.add_token()

            return Response(UrlInfoSerializer(url).data)
        else:
            return Response({'detail': 'Update forbidden'}, status=HTTP_403_FORBIDDEN)

api/views/UrlsView.py
from urllib.parse import urlsplit

from rest_framework.response import Response
from rest_framework.status import *

from api.views.ScraperApiView import ScraperApiView
from drf_yasg.utils import swagger_auto_schema
from api.serializers import *
from core.proxies import Url, Domain
from core.serializers import ConfigurationSerializer


class UrlsView(ScraperApiView):
    @swagger_auto_schema(
        request_body=UploadUrlRequestSerializer,
        responses={
            201: UrlInfoSerializer,
            400: HttpBadRequestSerializer,
            401: 'Wrong token or no token provided',
            403: 'Adding urls is forbidden'
        },
        operation_id='Upload URL'
    )
    def post(self, request):
        """
        API method to upload url for scraping

        """
        params = UploadUrlRequestSerializer(data=request.data)
        if not params.is_valid():
            return Response(HttpBadRequestSerializer(get_error_desc(params)).data, status=HTTP_400_BAD_REQUEST)

        pool = params.data['pool']
        if pool == 'public' and request.user.scraper.tokens == 0:
            return Response({'detail': 'No tokens'}, status=HTTP_403_FORBIDDEN)
        if pool == 'private' and not request.user.scraper.allow_private:
            return Response({'detail': 'Private pool is disallowed'}, status=HTTP_403_FORBIDDEN)

        url_value = params.data['url']
        domain, created = Domain.objects.get_or_create(
            hostname="{0.netloc}".format(urlsplit(url_value)),
            owner=request.user
        )
        url = Url.objects.create(owner=request.user, url=url_value, domain=domain)
        if pool == 'public':
            url.move_to_public(save=False)
            request.user.scraper.revoke_token()

        conf_type = params.data['conf_type']

        if conf_type:
            configuration = ConfigurationSerializer(data=request.data)

            if not configuration.is_valid():
                return Response(HttpBadRequestSerializer(get_error_desc(configuration)), status=HTTP_400_BAD_REQUEST)

            conf = configuration.save(user=request.user)
            if conf_type == 'domain':
                domain.configuration = conf
                domain.save()
            elif conf_type == 'url':
                url.configuration = conf

        ip_rate_rule = url.domain.get_ip_rate_rule()
        ip_rate_rule.rate_type = params.data['ip_rate_type']
        ip_rate_rule.rate_limit = params.data['ip_rate_limit']
        ip_rate_rule.save()

        url.save()
        return Response(UrlInfoSerializer(url).data, status=HTTP_201_CREATED)

    @swagger_auto_schema(
        query_serializer=GetUrlsRequestSerializer,
        responses={
            200: GetUrlsResponseSerializer,
            204: 'No URLs matching query',
            400: HttpBadRequestSerializer,
            401: 'Wrong token or no token provided',
        },
        operation_id='Get all URLs'
    )
    def get(self, request):
        scraper = request.user.scraper
        params = GetUrlsRequestSerializer(data=request.data)
        if not params.is_valid():
            return Response(HttpBadRequestSerializer(get_error_desc(params)), status=HTTP_400_BAD_REQUEST)

        limit = params.data['limit']
        pool = params.data['pool']

        if pool == 'private':
            query_set = scraper.get_private_urls()[:limit]
        elif pool == 'public':
            query_set = scraper.get_public_urls()[:limit]
        elif pool == 'waiting':
            query_set = scraper.get_waiting_urls()[:limit]
        else:
            query_set = scraper.get_urls()[:limit]

        urls_list = list(query_set)
        count = len(urls_list)
        if count == 0:
            return Response(status=HTTP_204_NO_CONTENT)
        else:
            return Response(GetUrlsResponseSerializer({'count': count, 'urls_list': urls_list}).data)

    @swagger_auto_schema(
            responses={
                200: 'Urls deleted',
                401: 'Wrong token or no token provided',
            },
            operation_id='Delete all URLs'
        )
    def delete(self, request):
        scraper = request.user.scraper
        scraper.get_domains().delete()
        scraper.get_urls().delete()
        return Response()

core/views/base.py
from django.core.paginator import Paginator
from django.shortcuts import render


class TemplateListView:
    def __init__(self, items_list, template, page=1, items_on_page=10):
        self.template = template
        self.items_list = items_list
        self.page = page
        self.items_on_page = items_on_page
        self.context = {}

    def add_extra(self, key, value):
        self.context[key] = value

    def render(self, request):
        paginator = Paginator(self.items_list, self.items_on_page)
        if not self.page in paginator.page_range:
            self.page = 1

        self.context['items_list'] = paginator.page(self.page).object_list
        self.context['paginator'] = paginator
        self.context['current_page'] = self.page

        return render(request, self.template, self.context)

core/views/home.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render


@login_required
def home(request):
    context = {
        'scraper': request.user.scraper,
        'android': 'android' in request.META['HTTP_USER_AGENT'].lower(),
    }

    return render(request, 'home.html', context)


def download_android(request):
    with open('files/scraper.apk', 'rb') as apk:
        response = HttpResponse(apk.read(), content_type="application/vnd.android.package-archive")
        response['Content-Disposition'] = 'inline; filename=scraper.apk'

    return response


@login_required
def delete_user(request):
    request.user.delete()
    logout(request)
    return redirect('login')


def landing_page(request):
    return render(request, 'landing.html')

core/views/ip_address.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from core.proxies import IPAddress
from .base import TemplateListView


@login_required
def get_all(request):
    scraper = request.user.scraper

    page = int(request.GET.get('page', '1'))

    items_list = list(scraper.get_ip_addresses())
    view = TemplateListView(items_list, 'ip/get_all.html', page=page)
    view.add_extra('ip_count', len(items_list))
    return view.render(request)


@login_required
def get(request, pk):
    scraper = request.user.scraper
    try:
        ip_address = IPAddress.objects.get(pk=pk)
    except IPAddress.DoesNotExist:
        if request.user.is_superuser:
            return redirect('admin_ips')
        else:
            return redirect('get_all_addresses')

    context = {
        'ip_address': ip_address,
        'connections_for_hour': ip_address.get_last_hour_connections().count(),
        'connections_for_day': ip_address.get_last_day_connections().count(),
        'rate_type': ip_address.get_rate_type_display(),
        'rate_limit': ip_address.rate_limit,
    }
    return render(request, 'ip/get.html', context)

core/templates/url/actions.html
<span>
    {% if url.is_scraped %}
    <small>Cannot move scraped target</small>
    {% else %}

        <b>Move to:</b>
        {% if user.scraper.allow_private %}

            {% if url.get_pool_display != 'Public' and user.scraper.tokens > 0 %}
            <div class="btn btn-sm btn-success" onclick="move_to_public({{ url.id }})">public</div>
            {% endif %}

            {% if url.get_pool_display != 'Private' %}
            <div class="btn btn-sm btn-primary" onclick="move_to_private({{ url.id }})">private</div>
            {% endif %}

        {% else %}

            {% if url.get_pool_display != 'Public' and user.scraper.tokens > 0 %}
            <div class="btn btn-sm btn-success" onclick="move_to_public({{ url.id }})">public</div>
            {% endif %}

        {% endif %}

        {% if url.get_pool_display != 'Waiting' %}
        <div class="btn btn-sm btn-secondary" onclick="move_to_waiting({{ url.id }})">waiting</div>
        {% endif %}

    {% endif %}

        <div class="btn btn-sm btn-danger" onclick="delete_url({{ url.id }})">delete</div>

</span>

core/templates/url/add.html
{% extends 'base/form_page.html' %}

{% block title %}Add URLs{% endblock %}

{% block includes %}
    {{ block.super }}
    {% load static %}
    <script src="{% static 'add_url.js' %}"></script>
{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <form method="POST" class=" w-75 m-5 p-5 border shadow-sm" enctype="multipart/form-data">
      <h4>Add urls:</h4>
      <hr>
      <div id="form_fields" class="p-1" style="max-height:400px; overflow-y:scroll; overflow-x:hidden">
          <input id="count" name="count" value="1" type="hidden">
          {% csrf_token %}
          <div class="form-group row">
              <label for="url_1" class="col-2 col-form-label">Url 1:</label>
              <div class="col-sm-10">
                  <input type="text" class="form-control" id="url_1" name="url_1" placeholder="Enter URL for scraping">
              </div>
          </div>
      </div>
      <div class="row mb-5">
        <div class="col-2"></div>
        <center class="col-sm-10 pr-4"><div class="btn btn-secondary btn-sm btn-block" onclick="add_field()">One more</div></center>
      </div>
        <button type="submit" class="btn w-25 btn-primary" onclick="return validate_all();">Add</button>
        <a href="{% url 'get_all_urls' %}" class="btn btn-secondary w-25">Cancel</a>
  </form>
</div>
{% endblock %}

core/templates/url/get.html
{% extends 'base/content_page.html' %}

{% block title %}Manage URL{% endblock %}

{% block includes %}
    {{ block.super }}
    {% load static %}
    <script src="{% static 'scrapurl.js' %}"></script>
{% endblock %}

{% block page_title %}
    <div class="p-3">
		<h1 style="display: inline-block;">Domain: {{ url.domain }}</h1>
		<a href="{% url 'get_domain' domain_id=url.domain.id %}">manage</a>
	</div><br>
{% endblock %}

{% block content_title %}
    <div class="mb-5"><h2>Url: {{ url }}</h2></div>
{% endblock %}

{% block content %}
	<form action="{% url 'update_url' url_id=url.id %}" method="post" class="w-50">
	<h4>Configurations:</h4>
	<hr>
    {% csrf_token %}
    {% for field in form_configs %}
      	 <div class="form-group row">
        	<div class="col">{{ field.label_tag }}</div>
        	<div class="col">{{ field }}</div>
      	</div>
    	{% endfor %}
    		<button type="submit" class="btn btn-primary mt-2 mb-2">Save for this URL</button>
    		<a href="{% url 'reset_url' url_id=url.id %}">
    			<button type="button" class="btn btn-secondary mt-2 mb-2">Use Domain configs</button></a>
  		</form>
{% endblock %}

{% block sidebar %}
    <div id="actions">
        <script>
            create_actions(new Map([
                ['Delete URL', { elem: 'div', onclick:'delete_url({{ url.pk }})', class:'btn-danger'}]
            ]));
        </script>
    </div>
{% endblock %}

core/templates/url/get_all.html
{% extends 'base/list_page.html' %}

{% block title %}
    My URLs
{% endblock %}

{% block includes %}
    {{ block.super }}
    {% load static %}
    <script src="{% static 'scrapurl.js' %}"></script>
{% endblock %}

{% block page_title %}
    <div class="p-3 mt-2 mb-2">
        <h3 style="display: inline-block;">Total domains: {{ domains_count }}</h3>
        <a class="ml-4" href="{% url 'get_all_domains' %}">View all</a>
    </div>
{% endblock %}


{% block content_title %}
    <h3>Your urls:</h3>
    <div id="filter">
        <script>
            create_filter(new Map([
                {% if user.scraper.allow_private %}
                ['Pool',['All','Public','Private','Waiting']],
                {% else %}
                ['Pool',['All','Public','Waiting']],
                {% endif %}
                ['Status',['All','Not scraped','Scraping','Scraped']]
            ]));
        </script>
    </div>
    <div class="row">
        <div class="col">
           URL
        </div>
        <div class="col-1">
            Status
        </div>
        <div class="col-1">
            Current pool
        </div>
        <div class="col-4">
            Actions
        </div>
    </div>
    <hr>
{% endblock %}

{% block list_item %}
{% with url=item %}
    <div class="col">
        <a href="{% url 'get_url' url_id=url.id %}">{{ url|truncatechars:60 }}</a>
    </div>
    <div class="col-1">
        {{ url.get_status_display }}
    </div>
    <div class="col-1">
        {{ url.get_pool_display }}
    </div>
    <div class="col-4">
        {% include 'url/actions.html' %}
    </div>
{% endwith %}
{% endblock %}

{% block sidebar %}
    <div id="actions"></div>
    <script>
        create_actions(new Map([
                ['Add new', {href:'{% url 'add_urls' %}',class:'btn-primary'}],
                ['Remove all', { elem: 'div', onclick:'delete_all()', class:'btn-danger'}],
                ['Upload', {href:'{% url 'upload_urls' %}',class:'btn-info'}]
            ]));
    </script>
{% endblock %}

core/templates/url/upload.html
{% extends 'base/form_page.html' %}

{% block title %}Upload URLS{% endblock %}
{% block includes %}
    {{ block.super }}
    {% load static %}
    <script src="{% static 'add_url.js' %}"></script>
{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <form method="post" class="m-5 p-5 border shadow-sm w-50" enctype="multipart/form-data">
      {% csrf_token %}

      <h4>Upload your URLs</h4><hr>

        <div class="row p-4">
            <label class="col btn btn-outline-primary btn-lg">
                <span id="file_button_text">Select file with URLs</span>
                <input type="file" id="urls_file" type="file" name="urls_file" onchange="handleFiles(this.files)" hidden>
            </label>
        </div>

      <div id="stats" class="row mb-5" style="visibility:hidden;">
          <div class="text-center col text-success" id="valid"></div>
          <div class="text-center col text-danger" id="invalid"></div>
      </div>

      <div class="row">
          <div class="col">
            <a class="btn btn-secondary btn-block" href="{% url 'get_all_urls' %}">Cancel</a>
          </div>
          <div class="col">
              <button id="submit_button" style="display:none" class="btn btn-primary btn-block" type="submit">Upload</button>
          </div>
      </div>
  </form>
</div>
<script type="text/javascript">
    var reader = new FileReader();
    reader.onload = function(fileContent){
        arrayOfLines = fileContent.target.result.match(/[^\r\n]+/g);
        display_statistic(arrayOfLines);
    }

    function display_statistic(urls_array){
        var valid_counter = 0;
        var invalid_counter = 0;
        for(i = 0; i < urls_array.length; i++){
            if(validate_url(urls_array[i])){
                valid_counter+=1;
            }else{
                invalid_counter+=1;
            }
        }
        if(valid_counter > 0){
            $("#invalid").html('Invalid urls:' + invalid_counter);
            $("#valid").html('Valid urls:' + valid_counter);
            $("#stats").attr("style","");
        }else{
            $("#stats").attr("style","visibility:hidden;");
            alert('No valid URLs found in this file, try another one');
        }
    }

    function handleFiles(files){
        var filename = files[0].name;
        if(filename){
            $("#file_button_text").html(filename.substr(0,20));
            $("#submit_button").attr("style","")
        }else{
            $("#file_button_text").html('Select file with URLs');
            $("#submit_button").attr("style","display:none")
        }
        reader.readAsText(files[0]);
    }
</script>
{% endblock %}